### ISSUE TITLE
Unable to connect to a private server

### ISSUE THREAD

**Issue by MayQueen33** [yuroyami/syncplay-mobile#101]
![Screenshot_2024-06-18-00-00-14-089_com reddnek syncplay](https://github.com/yuroyami/syncplay-mobile/assets/173081942/81e1a3cf-fad9-4718-a879-1c49d13c388b)
Always connecting........
It connects to official servers successfully. And my private server is accessible to Syncplay on PC.

**Comment by MayQueen33** [comment]
Netty without TLS
![Screenshot_2024-06-18-00-00-14-089_com reddnek syncplay](https://github.com/yuroyami/syncplay-mobile/assets/173081942/4a730db4-7138-4116-9e76-576b37f18abc)

Netty with TLS
![Screenshot_2024-06-18-00-22-03-958-edit_com reddnek syncplay](https://github.com/yuroyami/syncplay-mobile/assets/173081942/abd73312-4ea4-4331-8102-3fb18b5d961b)

Ktor with or without TLS
![Screenshot_2024-06-18-00-20-08-447-edit_com reddnek syncplay](https://github.com/yuroyami/syncplay-mobile/assets/173081942/da81d537-2448-4290-8f32-e44b5079bdc6)

**Comment by MayQueen33** [comment]
Maybe I can try turning off the password protection later.

**Comment by yuroyami** [comment]
The fix for this issue will be shipped in version 0.15.0
