### ISSUE TITLE
Is vlc android supported?

### ISSUE THREAD

**Issue by YodaSP** [yuroyami/syncplay-mobile#102]
Hi
I have a query
I would like to use syncplay with vlc android
I would like to know the steps on how to play a file in vlc alongwith syncplay android.
Kindly support to the earliest.

**Comment by yuroyami** [comment]
@YodaSP 
Syncplay comes with three built-in media players, and it only supports playback within the app itself—you can't hand off media to another app. But, VLC is one of these integrated players, you can switch between players on the home screen, just look for the player-switching button right above the "Join Room" button. The VLC integration is still in its experimental phase and hasn't undergone any testing yet, so it may not work reliably, so I recommend using mpv instead, as it offers nearly the same features and is the most stable option among the three.
