### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by b0s-at-works** [yuroyami/syncplay-mobile#47]
I'm ready to make Russian translation. What can I do to translate it?
Is there any Excel list with strings or something?
Also how about these strings to contain sprintf patterns to allow to make translation in right way?

**Comment by Reddnek** [comment]
For now, the translation file has some errors, out-dated texts, and some texts that aren't supporting translation yet. I will be working on fixing it by the time the next version is available, then I will bump up this issue and let you know when translation can be edited (and I will also explain the process of doing it). It's basically an XML file which can be edited with any text editor, it's pretty easy to edit. 

Also, refer to #30 for more info.

**Comment by b0s-at-works** [comment]
If I will have time, can I provide you even with current state of locale but anyway can I provide you file translated?

**Comment by Reddnek** [comment]
@b0s-at-works A lot of texts have been added in version 0.11.1 that are not within the translation file so even if you translate it now, it would be missing a lot of texts (especially for settings). 

I will be releasing a new version soon enough which will support full translation and I will mention you in this thread again

**Comment by yuroyami** [comment]
A ChatGPT-generated Russian translations were added in [v0.13.0](https://github.com/yuroyami/syncplay-mobile/releases/tag/v0.13.0). The file is [RuStrings.kt](https://github.com/yuroyami/syncplay-mobile/blob/master/shared/src/commonMain/kotlin/com/yuroyami/syncplay/lyricist/localizations/RuStrings.kt)

**Comment by b0s-at-works** [comment]
> @b0s-at-works A ChatGPT-generated Russian translations were added in [v0.13.0](https://github.com/yuroyami/syncplay-mobile/releases/tag/v0.13.0). The file is [RuStrings.kt](https://github.com/yuroyami/syncplay-mobile/blob/master/shared/src/commonMain/kotlin/com/yuroyami/syncplay/lyricist/localizations/RuStrings.kt)

Amazing!

**Comment by yuroyami** [comment]
@b0s-at-works Your contribution will be much appreciated. Regarding the strings, texts are all auto-resizeable, so their length should not be a problem at all :)

**Comment by b0s-at-works** [comment]
> @b0s-at-works Your contribution will be much appreciated. Regarding the strings, texts are all auto-resizeable, so their length should not be a problem at all :)

Thank you for answer! My pleasure!

**Comment by ivy-reps** [comment]
@yuroyami , can I ask questions about what some phrases means? For example `connectRoomnameC = "Room where you and your friends watch"` is about room where my friends already in and they are watching film there right now? Or they are watching for the room with that name which will be created by me?

**Comment by yuroyami** [comment]
@ivy-reps, thanks for showing such keen interest for contribution!

1- It's basically the same thing. Users have to put in the name of the room they want to create or join. Syncplay servers create rooms if you're the first one joining, or if the room already exists you join it.

3- Solo mode is literally just a video player, it is an offline mode to use one of the built-in video player backends (ExoPlayer or mpv). It works without internet and has nothing to do with Syncplay itself. 

4- Official Syncplay maintainers provide public servers which can be used by anyone, but sometimes the ping is too high in some locations around the world (since they're hosted in France I assume) which affects user experience. One can build their own self-hosted server using Syncplay official source code and let friends join said server.

5- The ChatGPT translations were generated before I introduced TLS support, this could be the case for many other texts which may also be outdated because the first thing I did in the new version was generating ChatGPT translations.

**Comment by ivy-reps** [comment]
> @ivy-reps, thanks for showing such keen interest for contribution!
> 
> 1- It's basically the same thing. Users have to put in the name of the room they want to create or join. Syncplay servers create rooms if you're the first one joining, or if the room already exists you join it.
> 
> 3- Solo mode is literally just a video player, it is an offline mode to use one of the built-in video player backends (ExoPlayer or mpv). It works without internet and has nothing to do with Syncplay itself.
> 
> 4- Official Syncplay maintainers provide public servers which can be used by anyone, but sometimes the ping is too high in some locations around the world (since they're hosted in France I assume) which affects user experience. One can build their own self-hosted server using Syncplay official source code and let friends join said server.
> 
> 5- The ChatGPT translations were generated before I introduced TLS support, this could be the case for many other texts which may also be outdated because the first thing I did in the new version was generating ChatGPT translations.


I think I just finished... I'm not satisfied with what I've done. But it's really hard to express some English meanings in Russian, with keeping English sentence structure. Does not matter. I'm always ready to fix something if you will need that.
As beginner, I'm satisfieid.

[EnStrings.txt](https://github.com/yuroyami/syncplay-mobile/files/14088577/EnStrings.txt)

Can't wait your release!

**Comment by ivy-reps** [comment]
> @ivy-reps, thanks for showing such keen interest for contribution!

@yuroyami, I think I just finished... I'm not satisfied with what I've done. But it's really hard to express some English meanings in Russian, with keeping English sentence structure. Does not matter. I'm always ready to fix something if you will need that.
As beginner, I'm satisfied. If you need I can send .patch of what changes I made to original Russian GPT version

[RuStrings.txt](https://github.com/yuroyami/syncplay-mobile/files/14103486/RuStrings.txt)


Can't wait your release!

**Comment by yuroyami** [comment]
@ivy-reps Thank you for your contribution! I will make sure to include your localization in the next release very soon.

**Comment by ivy-reps** [comment]
> @ivy-reps Thank you for your contribution! I will make sure to include your localization in the next release very soon.

Yeah babe!

**Comment by yuroyami** [comment]
@ivy-reps The Russian translation is now included in [v0.14.0](https://github.com/yuroyami/syncplay-mobile/releases/tag/v0.14.0). Thank you for your contribution! Feel free to update the translation file any time you want in this thread and I'll make sure to update it in the following releases respectively

**Comment by b0s-at-works** [comment]
> @ivy-reps The Russian translation is now included in [v0.14.0](https://github.com/yuroyami/syncplay-mobile/releases/tag/v0.14.0). Thank you for your contribution! Feel free to update the translation file any time you want in this thread and I'll make sure to update it in the following releases respectively

Thank you for finding time to implement that. I will take a look on how it will look like on the phone. Thank you very much.

**Comment by ivy-reps** [comment]
> @ivy-reps The Russian translation is now included in [v0.14.0](https://github.com/yuroyami/syncplay-mobile/releases/tag/v0.14.0). Thank you for your contribution! Feel free to update the translation file any time you want in this thread and I'll make sure to update it in the following releases respectively

Thank you for finding time to implement that. I will take a look on how it will look like on the phone. Thank you very much.
