### ISSUE TITLE
feature request: remember selected subtitle index when changing files

### ISSUE THREAD

**Issue by soredake** [yuroyami/syncplay-mobile#51]
It would be nice if syncplay-android can remember selected subtitle index so i wouldn't have to select it again when next file will be played.

**Comment by yuroyami** [comment]
this one used to be an actual feature in previous versions, i forgot to include it again after all the revamping. i will take that into account, thanks for the reminder

**Comment by yuroyami** [comment]
@soredake I am not sure if this is working again in [v0.13.0](https://github.com/yuroyami/syncplay-mobile/releases/tag/v0.13.0). Could you test it for me with both mpv and exo? I'll try to test it myself as well

**Comment by soredake** [comment]
@yuroyami I can't test this since shared playlist settings is broken for me https://github.com/yuroyami/syncplay-mobile/issues/87

**Comment by yuroyami** [comment]
@soredake It should also work when you're loading one similar file after another (since that's what happened during shared playlist index change)

**Comment by soredake** [comment]
Now subtitle index is remembered, it's been hard to test this since there are so many crashes in this version.

**Comment by yuroyami** [comment]
@soredake Do kindly report any crashes you're experiencing, I am currently using this version and it's crashing less often for me than the previous one. There are some departments that still require a lot of work to do such as the quick launch shortcuts and shared playlists
