### ISSUE TITLE
Give UI text outline/shadows to avoid blending with background

### ISSUE THREAD

**Issue by soredake** [yuroyami/syncplay-mobile#53]
Example of UI text blending with background:
![Без имени](https://user-images.githubusercontent.com/5204968/221357964-dcdfd044-9201-449d-b6e7-7d3b8c5ef64b.png)

**Comment by yuroyami** [comment]
There is a setting that allows you to adjust background opacity behind the chat texts, but now that you've mentioned this, outlines and shadows could be a better solution to this, i appreciate the suggestion

**Comment by yuroyami** [comment]
In [version (0.12.0)](https://github.com/yuroyami/syncplay-android/releases/tag/v0.12.0), added a subtle outline and shadow to the chat texts. After considering its potential impact on the app's performance, I have decided not to extend this enhancement to other UI elements. Therefore, I have chosen to skip implementing it for now.

**Comment by yuroyami** [comment]
@soredake Weird, I thought I added both an outline and a shadow. Thanks for raising this

**Comment by yuroyami** [comment]
Fixed in [v0.13.0](https://github.com/yuroyami/syncplay-mobile/releases/tag/v0.13.0)

There are 2 options now to add an outline, or a shadow, or both
