### ISSUE TITLE
Syncplay-android often can't find file in playlist if it's put in subdirectory under media directory

### ISSUE THREAD

**Issue by soredake** [yuroyami/syncplay-mobile#54]
If i put "<sdcard>/directory" into media directories list, and the put some files into "<sdcard>/directory/subdirectory" and add this files to playlist syncplay-android will have troubles finding them most of the time.

**Comment by yuroyami** [comment]
It does fail to get files sometimes which is why I'm rewriting it for the moment, also, there will be a new feature that requires the user to turn on 'All files access', to not need media directories anymore, and the app will then query the entire device instead. Given the fact that most devices are fast enough storage-wise, it will be a good alternative to manually add media directories.

**Comment by soredake** [comment]
> Given the fact that most devices are fast enough storage-wise,

Don't know about microsd cards with large amount of folders/files like mine.

**Comment by yuroyami** [comment]
@soredake It will be optional and not enforced, so media directories will always be a thing, to account for low-end devices and secondary storage like yours

Btw, does this issue happen when you're loading files from the main storage ? this might have sth to do with only secondary storages etc

**Comment by soredake** [comment]
>Btw, does this issue happen when you're loading files from the main storage ?

It seems not, tried several adding several files from internal storage, all loaded fine.

>this might have sth to do with only secondary storages etc

I discovered reason why file is not loading, if i join room with only one playlist item it will not load from internal storage or microsd, adding another file to playlist and switching files makes first playlist item load fine until restart.

**Comment by yuroyami** [comment]
Noted, thanks for the troubleshooting

**Comment by soredake** [comment]
Also this bug makes me unable to switch playlist items, it will just stay on currently open file, even if i remove this playlist item.

**Comment by yuroyami** [comment]
@soredake, revamping broke many stuff, i will revisit the whole shared playlist thing since i just decided to perform a complete re-write on it. Thanks for bringing this to light

**Comment by soredake** [comment]
I've updated issue title and description.

**Comment by yuroyami** [comment]
Though shared playlists are still "incubating" and unstable, the whole tree inside a media directory is searched in [v0.14.0](https://github.com/yuroyami/syncplay-mobile/releases/tag/v0.14.0).
