### ISSUE TITLE
syncplay-android can't play hevc 10-bit video

### ISSUE THREAD

**Issue by soredake** [yuroyami/syncplay-mobile#56]
Tested with `jellyfish-3-mbps-hd-hevc-10bit.mkv` from https://www.larmoire.info/jellyfish/

**Comment by yuroyami** [comment]
The app supports as many formats as the device internally supports especially when it comes to highly compressed formats like HEVC with high bit depth such as 10bit or 12bit. 

This will be automatically solved if at some point i make the app wrap ffmpeg just like VLC does

**Comment by soredake** [comment]
@soredake yeah, you're right, my device can't hardware decode hevc 10-bit, same video in vlc produces garbled output and lags very much, mx player plays it correctly, lags as well but slightly less.

**Comment by yuroyami** [comment]
Fixed in [version (0.12.0)](https://github.com/yuroyami/syncplay-android/releases/tag/v0.12.0) with the introduction of mpv.

**Comment by soredake** [comment]
@yuroyami i tried playing jellyfish sample and got only black screen with mpv, with anime encoded in 10bit i got same black screen and crash after seeking.

**Comment by yuroyami** [comment]
@soredake Seems like mpv is not falling back to software decoding when the hardware codec is missing, thanks for testing

**Comment by yuroyami** [comment]
@soredake I've added some mpv-related settings inside the room in [v0.13.0](https://github.com/yuroyami/syncplay-mobile/releases/tag/v0.13.0), where you can enable/disable hardware acceleration, and also use "gpu-next" rendering backend, I dont even know what it is but mpv claims it's a new improved rendering engine or something, it may help

Also, it seems like mpv libs weren't falling back to software acceleration (as mentioned in this mpv-android [release](https://github.com/mpv-android/mpv-android/releases/tag/2023-08-27))

Let me know if that helps with this case

**Comment by soredake** [comment]
>Also, it seems like mpv libs weren't falling back to software acceleration

Yeah, hevc 10 bit are still not working.

**Comment by yuroyami** [comment]
@soredake This seems more like a device issue to me. What's the test result on [mpv-android](https://github.com/mpv-android/mpv-android)

**Comment by soredake** [comment]
Correction, no videos are working without gpu-next option: https://github.com/yuroyami/syncplay-mobile/issues/85
And with gpu-next, 10-bit are finally working, although with unplayable framerate, vlc/mx player give me much better framerate, but that's a mpv-player problem, will report to them.

**Comment by soredake** [comment]
@soredake reported to upstream https://github.com/mpv-android/mpv-android/issues/855
