### ISSUE TITLE
syncplay-android: add profiles for connection settings and allow directly connecting to server

### ISSUE THREAD

**Issue by soredake** [yuroyami/syncplay-mobile#62]
Add profiles for a connection settings such as ip address/port/room name/password, show this profiles on map app screen, related: https://github.com/Syncplay/syncplay/issues/593

Also it will be nice if this profiles can be shown as shortcuts so i can drag this shortcut to homescreen and tap to connect to server directly without showing setting and tapping "join room", related: https://github.com/Syncplay/syncplay/discussions/597

**Comment by yuroyami** [comment]
The latest [version](https://github.com/yuroyami/syncplay-android/releases/tag/v0.12.0) now supports saving the config as both a dynamic shortcut (by long-clicking the main syncplay icon) and a pinned shortcut (which are shortcuts pinned to homescreen/launcher to quickly launch the room).

**Comment by yuroyami** [comment]
In [v0.14.0](https://github.com/yuroyami/syncplay-mobile/releases/tag/v0.14.0), I've added a new general setting to delete all current dynamic shortcuts (on both Android and iOS). Note that it doesn't work for home shortcuts appearing as app icons. This issue can be considered resolved.
