### ISSUE TITLE
Sound continues playing after closing pip window

### ISSUE THREAD

**Issue by soredake** [yuroyami/syncplay-mobile#67]
1. Add any video with sound to playlist.
2. Start it.
3. Trigger pip (by pressing home for example).
4. Close pip window
5. Sound will stop for some seconds but will start playing again even thought app/pip is closed.

**Comment by yuroyami** [comment]
Closing pip window should now pause the player in [v0.14.0](https://github.com/yuroyami/syncplay-mobile/releases/tag/v0.14.0).
