### ISSUE TITLE
Subtile size settings does nothing

### ISSUE THREAD

**Issue by soredake** [yuroyami/syncplay-mobile#69]
Tested with anime that i obviously can't share and with [this file](https://files.catbox.moe/fu97jx.webm) (subtitles work only with mpv with this file).

**Comment by yuroyami** [comment]
Subtitle size setting only works with side-loaded files in Exoplayer mode. By next version I hope I can get them to work with mpv too

**Comment by yuroyami** [comment]
Subtitle size now works for both exo and mpv in [v0.13.0](https://github.com/yuroyami/syncplay-mobile/releases/tag/v0.13.0)
