### ISSUE TITLE
"Forward" button is broken

### ISSUE THREAD

**Issue by soredake** [yuroyami/syncplay-mobile#70]
For me this button jumps 00:01 instead of actually forwarding:

https://github.com/yuroyami/syncplay-android/assets/5204968/e7161cbd-2870-4069-951e-d2f1eb657e45

**Comment by yuroyami** [comment]
Already noticed this, it's pretty annoying honestly. It will have been fixed in the next version

**Comment by yuroyami** [comment]
Fixed in [v0.13.0](https://github.com/yuroyami/syncplay-mobile/releases/tag/v0.13.0)
