### ISSUE TITLE
Leaving room and then joining it again results in crash

### ISSUE THREAD

**Issue by soredake** [yuroyami/syncplay-mobile#72]
Using 0.12.0.

How to reproduce:
1) Join room.
2) Leave room by pressing "Back" button for example.
3) Join room again.
4) Crash.

https://github.com/yuroyami/syncplay-android/assets/5204968/e4c79782-c41a-4d60-aba1-0990ca1b08d8

**Comment by yuroyami** [comment]
Fixed in [v0.13.0](https://github.com/yuroyami/syncplay-mobile/releases/tag/v0.13.0)
