### ISSUE TITLE
Add brightness/volume swipe gestures

### ISSUE THREAD

**Issue by soredake** [yuroyami/syncplay-mobile#74]
Example usage of brightness/volume swipe gestures from revanced youtube:

https://github.com/yuroyami/syncplay-android/assets/5204968/9f59dd84-cab7-4f39-9a89-db692e2eea61

https://github.com/yuroyami/syncplay-android/assets/5204968/adee489d-fa38-4bf4-a529-d6880a2594fd

Example brightness/volume swipe gestures settings from revanced youtube:
![Screenshot_20230609-205254_YouTube](https://github.com/yuroyami/syncplay-android/assets/5204968/98290c94-0cef-46b2-9ec2-933f0bac3e0a)

**Comment by yuroyami** [comment]
Added in [v0.13.0](https://github.com/yuroyami/syncplay-mobile/releases/tag/v0.13.0), they're enabled with the double-tap gestures altogether
