### ISSUE TITLE
syncplay-android is still active despite app is minimized

### ISSUE THREAD

**Issue by soredake** [yuroyami/syncplay-mobile#76]
1) Start app
2) Add file to playlist
3) Minimize app (i pressed "home" button)
4) Start playing item on another device while being in room
5) You will hear sound from app despite it being minimized.

**Comment by yuroyami** [comment]
Events will not get passed to player when it is minimized in [v0.14.0](https://github.com/yuroyami/syncplay-mobile/releases/tag/v0.14.0). Let me know if it's fixed
