### ISSUE TITLE
Subtitle and Audio channel switching not working (JellyFin Stream)

### ISSUE THREAD

**Issue by g-l-i-t-c-h-o-r-s-e** [yuroyami/syncplay-mobile#77]
Hey there, I have a movie with English and Japanese subs/audio inside; that I'm streaming on a jellyfin server.
They show up as options in the app when I press the button to switch them, 
but it says `null [EN]` and `null [JN]` for the audio.
I can switch them just fine with mpv and vlc player, even with the mpv app on android.
The video stream is HEVC, audio is AAC and subtitles are ASS format.

Is there any way to force mpv as the video player? This **should** fix the issue in theory.
Many thanks for your time!

**Comment by g-l-i-t-c-h-o-r-s-e** [comment]
Just noticed the github release has an MPV option now, and that does indeed remedy this issue

**Comment by yuroyami** [comment]
`mpv`, albeit experimental, is currently the default and recommended player now. Every release after `0.12.0` will be distributed with mpv-engine, and there will always exist an `exo-only` flavor APK just in case the mpv version doesn't work well. All in all, I'd suggest against the use of ExoPlayer anyway. 

libVLC will probably also be supported some time in the future.

Regarding your issue on switching tracks, I assume the media you're trying to play is an HTTPs stream of some kind, HLS? DASH?

**Comment by yuroyami** [comment]
Closing this considering that mpv is the default (and strongly recommended) backend now, and the fact that syncplay-mobile incorporates multiple players to overcome various limitations and differences between these players
