### ISSUE TITLE
Double tap to seek broken

### ISSUE THREAD

**Issue by xpt1x** [yuroyami/syncplay-mobile#78]
While using double tap to seek:

While forwarding: rewinds position to 00:10s (**BROKEN**)
While rewinding: works as expected

**Comment by soredake** [comment]
https://github.com/yuroyami/syncplay-android/issues/70

**Comment by yuroyami** [comment]
Fixed in [v0.13.0](https://github.com/yuroyami/syncplay-mobile/releases/tag/v0.13.0)
