### ISSUE TITLE
Can you add the Spanish language?

### ISSUE THREAD

**Issue by DoncanC** [yuroyami/syncplay-mobile#82]
Hello, I love what you have done here, and I would like to contribute my bit with the Spanish language.

I already made the translation for version 0.12 and I hope it can work and I really don't know if it can be implemented, I hope so.
I hope to have some answer to know if what I did was right or if something needs to be fixed.

I repeat, thank you very much for your work.

PS: I can't upload in XML format, so I change it to TXT, I just change the extension.
[strings.txt](https://github.com/yuroyami/syncplay-android/files/13716865/strings.txt)

**Comment by yuroyami** [comment]
Thank you for your contribution! The upcoming localization for version 0.13.0 might have a few additional strings that are not present in the current `strings.xml`, but this will do for now. I might also use a weblate template for real-time localization for anyone who wanna contribute with more languages in the future.

Nonetheless, I will use your file for now, it should cover about 90% of the strings.

**Comment by DoncanC** [comment]
Understood!

I will be here to translate whatever is necessary for Spanish in each update.

Thank you so much. ^-^

**Comment by yuroyami** [comment]
@DoncanC Your localization is implemented in [v0.13.0](https://github.com/yuroyami/syncplay-mobile/releases/tag/v0.13.0).

Some texts may be missing on the UI, I am lazy to go through all the components of the UI and see what's really missing and whats not. But anyway, localizations now are not `.xml` but rather `.kt` (Kotlin files), the basis remains the same.

You can find the spanish locale here: [EsStrings.kt](https://github.com/yuroyami/syncplay-mobile/blob/master/shared/src/commonMain/kotlin/com/yuroyami/syncplay/lyricist/localizations/EsStrings.kt)

You can continue this thread whenever you want to modify the texts, and I will be sure to include them by the next version. There are many texts that were missing so I used ChatGPT to translate them, they probably sound bad so feel free to fix anything. I will close this for now.

Thank you for the contribution !

**Comment by coqre** [comment]
How do I translate what is missing?
Sorry to ask, I'm new to this. 😅

Which one do I take as a reference to continue? Because the final file seems to be incomplete in the Spanish translation. :/

**Comment by yuroyami** [comment]
@coqre You can find the files for all languages under this [directory](https://github.com/yuroyami/syncplay-mobile/tree/master/shared/src/commonMain/kotlin/com/yuroyami/syncplay/lyricist/localizations). You can take `EnStrings.kt` as reference as it is the English one which is always the complete one. Based on it, you can edit `EsStrings.kt` to add your missing/incomplete strings and attach it here. I will include it with the next version although i am not sure when that is going  to be precisely. Thanks for your contribution :))
