### ISSUE TITLE
File is still playing when leaving room

### ISSUE THREAD

**Issue by soredake** [yuroyami/syncplay-mobile#84]
1) Install [v0.13.0](https://github.com/yuroyami/syncplay-mobile/releases/tag/v0.13.0) version
2) Set backend to mpv.
3) Join room.
4) Play any file.
5) Leave room.
6) Sound is still playing.

**Comment by yuroyami** [comment]
Should be resolved in [v0.14.0](https://github.com/yuroyami/syncplay-mobile/releases/tag/v0.14.0). Let me know if it persists
