### ISSUE TITLE
Move "skip 1 minute 30 seconds" button to main screen

### ISSUE THREAD

**Issue by soredake** [yuroyami/syncplay-mobile#86]
Right now you need to do 4 taps to do skip, which is annoying.

New possible locations for this button:
![Screenshot_20240106-192844](https://github.com/yuroyami/syncplay-mobile/assets/5204968/410f90d6-3bdb-428e-abba-3b190b0dfca8)

**Comment by yuroyami** [comment]
@soredake This behavior is now implemented in version 0.15.0. You can choose to place the "custom skip button" on the main player screen, and you can also adjust the duration it skips. This can be done via in-room preferences (In-room preferences **->** Player Settings)
