### ISSUE TITLE
"Add folder" button in shared playlist settings is not working in 0.13.0

### ISSUE THREAD

**Issue by soredake** [yuroyami/syncplay-mobile#87]

**Comment by yuroyami** [comment]
Related to deactivating shared playlist feature (#88)

**Comment by yuroyami** [comment]
Shared Playlists are reactivated but are still "`incubating`". Media directories can be added now in [v0.14.0](https://github.com/yuroyami/syncplay-mobile/releases/tag/v0.14.0).
