### ISSUE TITLE
Can't switch audio and subtitles

### ISSUE THREAD

**Issue by Grandark1231** [yuroyami/syncplay-mobile#94]
First of all, sorry that i'm not very knowledgeable about this.

I'm using version 0.12.0, and i can't change my file's audio and subtitle. It worked just fine when i'm watching it alone on my vlc.

I tried to download the latest update but none of them would let me join a room. Is there anyway to fix this using the version i'm using right now?

![Screenshot_20240319_093533_Syncplay](https://github.com/yuroyami/syncplay-mobile/assets/163976582/91bf0296-4c05-4399-bf7e-36fc2390e2a5)

**Comment by yuroyami** [comment]
Hi @Grandark1231, the app comes with two video players (namely ExoPlayer and mpv), does the problem occur on both video engines ?

For the issue of joining the room in the latest version, I believe it may be linked to the fact that your room and server are password-protected (#94), do you confirm this ?

**Comment by yuroyami** [comment]
@Grandark1231 

It seems you're currently using the `exo-only` variant, which exclusively features the ExoPlayer engine. However, I must note that I consider this variant deprecated and not recommended at this time, as I'm neither testing it nor implementing any new features or fixes for it.

On the [0.12.0 release page](https://github.com/yuroyami/syncplay-mobile/releases/tag/v0.12.0), you'll encounter two variants:
- The standard variant, which includes two player engines and is available in four different architectures (please refer to the last paragraph of the release notes).
- The exo-only variant, which one might select if they strongly prefer ExoPlayer over mpv.

Get one of the other four APKs, specifically the one designed for your phone's architecture. After doing so, the engine switch button should become visible.

**Comment by Grandark1231** [comment]
> @Grandark1231
> 
> It seems you're currently using the `exo-only` variant, which exclusively features the ExoPlayer engine. However, I must note that I consider this variant deprecated and not recommended at this time, as I'm neither testing it nor implementing any new features or fixes for it.
> 
> On the [0.12.0 release page](https://github.com/yuroyami/syncplay-mobile/releases/tag/v0.12.0), you'll encounter two variants:
> 
> * The standard variant, which includes two player engines and is available in four different architectures (please refer to the last paragraph of the release notes).
> * The exo-only variant, which one might select if they strongly prefer ExoPlayer over mpv.
> 
> Get one of the other four APKs, specifically the one designed for your phone's architecture. After doing so, the engine switch button should become visible.

It worked after i used the arm64-v8a version. Thank you very much!
